name: pipeline de pruebas
on:
  push:

jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Verifica contenido del repositorio
        run: |
          echo "Este es el contenido del repositorio"
          tree
      - name: Verifica variables
        run: |
          echo "El valor de la variable MI_VAR es ${{ vars.MI_VAR }}"
      - name: Verifica secretos
        run: |
          echo "El valor del secreto MI_SECRETO es ${{ secrets.MI_SECRETO }}"
