name: pipeline de pruebas
on:
  push:

jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Verifica contenido del repositorio
        run: |
          echo "Este es el contenido del repositorio"
          tree
      - name: Verifica variables
        run: |
          echo "El valor de la variable MI_VAR es ${{ vars.MI_VAR }}"
      - name: Verifica secretos
        run: |
          echo "El valor del secreto MI_SECRETO es ${{ secrets.MI_SECRETO }}"
  instalacion:
    needs: prueba
    runs-on: ubuntu-latest
    steps:
      - name: Verificar Node
        run: |
          node --version
      - name: Verificar Java
        run: |
          java -version
      - name: Instalar Node 24
        uses: actions/setup-node@v7
        with:
          node-version: '24'
      - name: Instalar Java 24
        uses: actions/setup-java@v6
        with:
          java-version: '24'
          distribution: temurin
      - name: Verificar Node
        run: |
          node --version
      - name: Verificar Java
        run: |
          java -version
  despliegue:
    needs: instalacion
    runs-on: ubuntu-latest
    steps:
      - name: despliegue simulado
        run: |
          echo "Aca se ejecutada el despliegue"
